### ISSUE TITLE
🔨 [FIX] 다른탭에서 기록탭으로 돌아올 때 goalCategory 포커스 오류 수정 및 화면 연결

### ISSUE THREAD

**Issue by wngus4296** [TeamPOME/POME-iOS#48]
## 🐞 버그 설명
<img width="300" alt="image" src="https://user-images.githubusercontent.com/58043306/179006550-d937d423-2c43-4ec8-aebe-5ca3b405929f.png">

## 👛 작업 브랜치
- fix/#48-UI-Write-goalCategoryFocus

## 📝 To-do
- [x] 포커스 오류 수정..
- [x] 플러스 버튼 셀로 변경
- [x] 유진언니의 goalCard 연결
- [x] 목표 카드 높이 기기대응 추가
- [x] 카드 탭 화면 전환
- [x] 네비바 백버튼 액션 추가
- [x] 액션시트 연결
- [x] 알럿 연결
