### ISSUE TITLE
✨ [FEAT] 기록 글쓰기 UI 뷰 구현

### ISSUE THREAD

**Issue by wngus4296** [TeamPOME/POME-iOS#68]
## 👛 Feature Issue
기록 글쓰기 UI 뷰를 구현합니다. 

## 👛 작업 브랜치
- feature/#68-UI-Write-record

## 📝 To-do
- [ ] 목표 목록 바텀시트 구현
- [ ] 해당 목표 기간에 따른 캘린더 구현
- [ ] 키보드 처리
- [ ] 감정남기기
- [ ] 완료 뷰
- [ ] 작성 그만두기 알럿 연결
