### ISSUE TITLE
✨ [FEAT] 기록탭 메인뷰 UI 구성

### ISSUE THREAD

**Issue by wngus4296** [TeamPOME/POME-iOS#8]
## 👛 Feature Issue
기록탭 메인뷰 ui를 구성합니다.

## 👛 작업 브랜치
- feature/#8 -UI-Write-main

## 📝 To-do
- [x] 상단 목표 CV 구현
- [x] 목표 없을 때 empty view 구현
- [x] 감정을 남겨주세요 버튼 구현
- [x] 씀씀이 CV 구현

**Comment by dev-jungbin** [comment]
아자아자 팟팅이닷!
